### PR TITLE
Updates cached-habitat to add lfr and add straying capacity to wr

### PR DESCRIPTION
**Pull request by ErinCain**

### CODE REVIEW

**Comment by thesadie** [comment]
closes #8

**Comment by thesadie** [comment]
Deer creek was used as the basis to approximate habitat in other areas, need to update documentation and floodplain lengths source data before rerunning data caching for all impacted watersheds.

**Comment by thesadie** [comment]
- [x] @ErinCain plz build vignettes and pkgdown site - (i was having too many problems with rgdal install)
- [x] @ergz plz review the plots and summary stats on `data-raw/qc.R` after building the package to confirm that nothing looks weird to you value wise

After you are both done with those tasks, this is ready to merge into main and release

**Comment by ErinCain** [comment]
Thanks for doing all that Sadie!!! I rebuilt the site and vignettes. @thesadie do you want the `total_wetted_area.Rmd` vignette added as an article on the site?

**Pull request merged**
